
FROM ruby:3.2.2

ENV LANG C.UTF-8
ENV TZ Asia/Tokyo
ENV RAILS_ENV=development

RUN apt-get update -qq && apt-get install -y \
  ca-certificates curl gnupg postgresql-client vim nano

WORKDIR /app

COPY Gemfile Gemfile.lock ./
RUN gem install bundler && bundle install
COPY . .

CMD ["bin/dev"]
